name: CI Checks

on:
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn install
      - name: Run ESLint
        run: yarn run lint

  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: |
            yarn install
            yarn serve-dev
          wait-on: 'http://localhost:8080'
          command: yarn run test:e2e:run
