name: Cypress E2E Tests
on:
  pull_request:
jobs:
  eslint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn run lint
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: |
            yarn install
            yarn serve-dev
          wait-on: 'http://localhost:8080'
          command: yarn run test:e2e:run
