name: Build and Push Docker Image

on:
  release:
    types: [created]

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/serj-tubin-vue:$GITHUB_REF_NAME

    - name: Notify the server to redeploy via webhook
      run: |
        curl -v https://serj-tubin.com/webhook/st-vue/redeploy \
          -X POST \
          -H "Authorization: Bearer ${{ secrets.REDEPLOY_WEBHOOK_SECRET_TOKEN }}" \
          --retry 5 --retry-delay 2 --retry-max-time 60
